export const SECOND_MILLISECONDS = 1000;
export const MINUTE_MILLISECONDS = 60 * SECOND_MILLISECONDS;
export const HOUR_MILLISECONDS = 60 * MINUTE_MILLISECONDS;
export const DAY_MILLISECONDS = 24 * HOUR_MILLISECONDS;
